name: Update automatically from Public Health Wales

on:
  repository_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "10,30,50 * * * *"

jobs:
  update-phs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update PHW
        run: |
          ./tools/crawl_all.py PHW
          ./tools/convert_sqlite_to_csvs.py
      - name: Set variable to check if anything changed
        id: decide_variable
        run: |-
          git diff HEAD data/*.csv
          echo "$(git diff --quiet HEAD data/*.csv; echo $?)"
          echo "##[set-output name=changed;]$(git diff --quiet HEAD data/*.csv; echo $?)"
      - name: Commit files
        if: steps.decide_variable.outputs.changed != 0
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data
          git commit -m "Update for $(date) for PHW"
      - name: Push changes
        if: steps.decide_variable.outputs.changed != 0
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
